- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2023031414033887150000000a.cgbiymybzdx7.eu-west-3.rds.amazonaws.com"
    login_user: "admin"
    login_password: "PassWord"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-2023031414033887150000000a.cgbiymybzdx7.eu-west-3.rds.amazonaws.com" }
    - { regexp: '^admin', line: "admin" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "PassWord" }


